### ISSUE TITLE
Error Updating to 2.4

### ISSUE THREAD

**Issue by ArianaDulac** [Contentify/Contentify#359] opened 2018-05-19 02:36 UTC
Updating the database...Could not execute the database query: Duplicate column name 'country_id'
Error: Code 42S21

**Comment by niclasreich** [comment] 2018-05-22 11:03
Duplicate of #352

**Comment by chriskonnertz** [comment] 2018-05-22 21:35
Yes this seems to be a dupclicate. However, I assume ArianaDulac does not speak German so #352 does not help here.

**Comment by chriskonnertz** [comment] 2018-05-22 21:37
@ArianaDulac Did you try to run the update twice? The error occurs when you do that, because the new colum "coutnry_id" has already been created so it cannot create it again.

Quick & dirty work-around: Go to the update script and remove the line.
https://github.com/Contentify/Contentify/blob/2.4/public/update.php#L85

**Comment by ArianaDulac** [comment] 2018-05-24 02:03
Sooo, I ended up doing a fresh install of 2.4 and now I get the errors 

(1/2) ErrorException

include(directoryforcontentify/vendor/composer/../../app/Modules/Partners/Partnercat.php): failed to open stream: No such file or directory

(2/2) ErrorException
include(directoryforcontentify/vendor/composer/../../app/Modules/Partners/Partnercat.php): failed to open stream: No such file or directory (View: directoryforcontentify/app/Modules/MorpheusTheme/Resources/Views/layout.blade.php)

**Comment by chriskonnertz** [comment] 2018-06-01 10:14
Hello,

I believe I finally have a fix for this bug. I will commit it later this day.

**Comment by chriskonnertz** [comment] 2018-06-01 20:10
Hello,

please run `php composer.phar dumpautoload` per console.

**Closed as completed by chriskonnertz** 2018-06-01 20:10 UTC
Labels: bug
