### ISSUE TITLE
News Date Issue

### ISSUE THREAD

**Issue by EazYKevin** [Contentify/Contentify#176] opened 2017-06-17 22:07 UTC
Hello Again

I Think i found a new bug of some kind.

but some times some of my news, gets their updated date changed, when even not have updated any one of them.

maybe an easy fix would be to sort the news at the front page after, published_at date, the the bug maybe not happen, but i cant seem to find the file to change it in my self ?

you know anything to this bug ?

and is there supposed to be a pagination for the news at the frontpage ?

best regrads 
EazY (eShooting.dk)

**Comment by EazYKevin** [comment] 2017-06-22 20:10
you anything about this issue ?

**Comment by chriskonnertz** [comment] 2017-07-31 16:16
Hello,

> you know anything to this bug ?

Unfortunately I do not know anything about this bug. :/

> and is there supposed to be a pagination for the news at the frontpage ?

No, that is not on the roadmap.

However, it should not be that hard to implement. Add the pagination HTML code and add apgination to the news controller.

**Comment by chriskonnertz** [comment] 2019-03-13 11:50
Closing this issue since it is very old and most likely a duplicate of similar issues.

**Closed as completed by chriskonnertz** 2019-03-13 11:50 UTC
Labels: bug, question
