### ISSUE TITLE
Soo apprently github closed my last post...

### ISSUE THREAD

**Issue by lolbob181** [Contentify/Contentify#82] opened 2016-11-08 12:58 UTC
Ye the last post got closed soo the reply to the last answer i was given by the contentify owner is it is enabled http://prntscr.com/d4m2k5

**Comment by chriskonnertz** [comment] 2016-11-09 21:01
I will investigate but I have no time to do it today. I hope I will bea ble to do it tomorrow.

**Comment by lolbob181** [comment] 2016-11-10 19:21
okay but help

**Comment by romcika5** [comment] 2016-11-11 18:23
really weird, becouse in my server everythings works fine...

**Comment by chriskonnertz** [comment] 2016-11-11 20:49
Yeah, that is my problem as well. I cannot fix the bug because I cannot reproduce the error. :(

**Comment by chriskonnertz** [comment] 2016-11-11 20:55
@lolbob181 
Maybe this is a problem with permissions. You wrote:

>  a problem with users editing there profiles when they go to click save they get this

I assume this happens when users try to upload images?

If so, take a look at these directories:

```
publi/uploads/users
public/uploads/users/80
```

Is the CMs allowed to write into them (=create files)? Because in these directories it wants to save the uploaded images and so it needs write permissions (CHMOD 777).

**Comment by lolbob181** [comment] 2016-11-11 23:19
Will try I think it's on images too

**Comment by lolbob181** [comment] 2016-11-12 18:36
@chriskonnertz I found the problem.
It says FileInfo extension is missing but idk how to install it am on CPanel latest verison and idk the ssh root password of the machine soo please help

**Comment by krysennn** [comment] 2016-11-12 19:24
What is the name of your hoster ??

**Comment by lolbob181** [comment] 2016-11-13 12:24
Freemancode

**Comment by krysennn** [comment] 2016-11-13 12:37
I dont found any FAQ for your hoster.. So make support ticket..

**Comment by lolbob181** [comment] 2016-11-13 21:13
Okay while am getting that fixed i changed the banner and its small any tips http://prntscr.com/d6vav4 180 x 180 is small then that

**Comment by lolbob181** [comment] 2016-11-15 01:26
Halp

**Comment by romcika5** [comment] 2016-11-15 04:41
U really not good in website building so leave this thing for another guys...

**Comment by krysennn** [comment] 2016-11-15 06:12
@lolbob181 Contentify is CMS so you can edit, delete or add some content like news, cups, matchs, team or edit title, logo... 
But if you are unsatisfied you can edit the code but it's for avanced users and we can help you for fix bug or install but we have not any time for help you to edit the template for you.

**Comment by romcika5** [comment] 2016-11-15 06:16
@krysennn exactly!

**Comment by lolbob181** [comment] 2016-11-17 12:33
I fixed that i have also been having issues with the admin panel when i login to the admin account and go into the admin panel and i like press something like news or members etc it just tells me to login again is it a bug :O

**Comment by krysennn** [comment] 2016-11-17 15:43
With my fresh install of Contentify i haven't got the error ...
Are you sure you have installed Contentify with all prerequisite ?

**Comment by lolbob181** [comment] 2016-11-18 10:22
I just don't have fileinfo installed

**Comment by krysennn** [comment] 2016-11-20 07:22
I think it's problem with your hosting... 
I think your solution it's to stop your hosting, buy VPS (digitalocean, scaleway) and install Contentify with script proposed by Chris
You will get hosting will all prerequisite and you will get no error.. 

If you want change we can help you ;)

**Comment by chriskonnertz** [comment] 2016-11-20 09:13
> I just don't have fileinfo installed

Well if PHP extensions miss the CMS cannot workproperly. Imagine you build a car but without headlamps. Everything will work until that night when you drive on the highway and no one can see you in the dark. Sooner or later someone will crash into your car...

We can provide bugfixes for actual bugs of the CMS and we can try to provide hints if you have trouble to install the CMS. But we cannot configurate your server, this task is up to you or to your hoster.

If you do not have access and your hoster does not help you, please consider to use another server. For a typical eSports website you do not need expensive hardware. Find a cheap server that allows you access to its configuration. Depending on what you consider to be "cheap", I recommend [digitalocean.com](https://www.digitalocean.com/pricing/#droplet). They offer virtual servers beginning with 5 USD. The Contentify demo websites run with droplets of this type. However, this server might be oversized if you jsut want to play around or only host a website with few traffic/visitors. There are plenty of even cheaper hosters out there.

I'll close this issue for now since I feel that this issue is becoming to huge. If you have more questions o need help with something else, do not hesistate to create a new issue.

**Closed by chriskonnertz** 2016-11-20 09:13 UTC
Labels: bug
