### ISSUE TITLE
Add support get5 csgo

### ISSUE THREAD

**Issue by vilchez521** [Contentify/Contentify#454] opened 2018-11-10 11:57 UTC
Can this be possible?

**Comment by mrc4tt** [comment] 2018-11-10 12:08
Come with more information, about why you need get5 CSGO added on Contentify? Are you talking about "embed" the get5-panel? ;)

**Comment by chriskonnertz** [comment] 2018-11-10 12:20
Hello,

"get5 csgo" = https://github.com/splewis/get5 ?

**Comment by vilchez521** [comment] 2018-11-10 12:35
I need that page is automatically able to launch the game on the server, I take this opportunity to ask also for the classification, I am not able to find it on the page...

**Comment by mrc4tt** [comment] 2018-11-10 12:39
> I need that page is automatically able to launch the game on the server, I take this opportunity to ask also for the classification, I am not able to find it on the page...

Yeah...i don't think it will be created. ;) you can create your own. ;) and you need to know howto(code) API ;) before it will works (as automatically)

**Comment by vilchez521** [comment] 2018-11-10 12:43
And regarding the classification? Could you implement on the page? This is important for us...

**Comment by mrc4tt** [comment] 2018-11-10 13:11
The problem is, if Contentify needed to "make" get5-WEB base to works on Contentify, will require about they will make a "script" so the "python" is running. ;) 

*\ OR you need to host it youself (or linking the public page) to being "embeded" ;) 

@chriskonnertz - i think he means this > https://github.com/splewis/get5-web

tr;dr dunno about get5-web supporting API.

**Comment by vilchez521** [comment] 2018-11-11 09:11
Exactly, this page what it does is throw a game when you dés to play.
My idea is that when the time comes for the game, the page will be able to launch the game according to the teams that have in that game.

Do not answer the second question about the classification, I still do not be able to find the classification of the League on the page, can you help me?

**Comment by andakawa** [comment] 2018-11-27 20:07
You'll need to set this service up on your webserver and embedd it on a contentify-page but as a feature-request I guess that this is way out of scope.

**Comment by chriskonnertz** [comment] 2018-11-27 22:39
Yeah I think the same way. I mean even *if* we assume this is in the scope of the general development of this CMS, it would have a very low priority. So I recommend to try to find an external coder who implements this feature.

**Closed as completed** 2019-03-13 12:23 UTC
Labels: question
