### ISSUE TITLE
Error 500 while installing new contentify 2.0

### ISSUE THREAD

**Issue by romcika5** [Contentify/Contentify#79] opened 2016-11-02 16:52 UTC
Hi. I'm try to install contentify 2.0. And i'm getting error 500. My laravel.log looks like that:

`[2016-11-02 17:48:57] production.ERROR: exception 'PDOException' with message 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php:55
Stack trace:
#0 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/Connector.php(55): PDO->__construct('mysql:host=loca...', 'root', '', Array)
#1 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/MySqlConnector.php(24): Illuminate\Database\Connectors\Connector->createConnection('mysql:host=loca...', Array, Array)
#2 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connectors/ConnectionFactory.php(61): Illuminate\Database\Connectors\MySqlConnector->connect(Array)
#3 [internal function]: Illuminate\Database\Connectors\ConnectionFactory->Illuminate\Database\Connectors\{closure}()
#4 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(924): call_user_func(Object(Closure))
#5 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(792): Illuminate\Database\Connection->getPdo()
#6 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(677): Illuminate\Database\Connection->reconnectIfMissingConnection()
#7 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php(349): Illuminate\Database\Connection->run('select * from `...', Array, Object(Closure))
#8 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1610): Illuminate\Database\Connection->select('select * from `...', Array, true)
#9 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1596): Illuminate\Database\Query\Builder->runSelect()
#10 /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Query/Builder.php(1577): Illuminate\Database\Query\Builder->get(Array)
#11 /var/www/html/contentify/Config.php(83): Illuminate\Database\Query\Builder->first()
#12 /var/www/html/contentify/ModuleRoute.php(48): Contentify\Config::get('modules.namespa...')
#13 /var/www/html/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(217): Contentify\ModuleRoute->context('Config')
#14 /var/www/html/app/Modules/Config/Http/routes.php(3): Illuminate\Support\Facades\Facade::__callStatic('context', Array)
#15 /var/www/html/app/Modules/Config/Http/routes.php(3): Contentify\Facades\ModuleRoute::context('Config')
#16 /var/www/html/app/Modules/Config/Providers/RouteServiceProvider.php(12): require('/var/www/html/a...')
#17 [internal function]: App\Modules\Config\Providers\RouteServiceProvider->App\Modules\Config\Providers\{closure}(Object(Illuminate\Routing\Router))
#18 /var/www/html/vendor/laravel/framework/src/Illuminate/Routing/Router.php(398): call_user_func(Object(Closure), Object(Illuminate\Routing\Router))
#19 /var/www/html/app/Modules/Config/Providers/RouteServiceProvider.php(13): Illuminate\Routing\Router->group(Array, Object(Closure))
#20 [internal function]: App\Modules\Config\Providers\RouteServiceProvider->map(Object(Illuminate\Routing\Router))
#21 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#22 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(72): Illuminate\Container\Container->call(Array)
#23 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Support/Providers/RouteServiceProvider.php(31): Illuminate\Foundation\Support\Providers\RouteServiceProvider->loadRoutes()
#24 [internal function]: Illuminate\Foundation\Support\Providers\RouteServiceProvider->boot(Object(Illuminate\Routing\Router))
#25 /var/www/html/vendor/laravel/framework/src/Illuminate/Container/Container.php(507): call_user_func_array(Array, Array)
#26 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(757): Illuminate\Container\Container->call(Array)
#27 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(740): Illuminate\Foundation\Application->bootProvider(Object(App\Modules\Config\Providers\RouteServiceProvider))
#28 [internal function]: Illuminate\Foundation\Application->Illuminate\Foundation\{closure}(Object(App\Modules\Config\Providers\RouteServiceProvider), 34)
#29 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(741): array_walk(Array, Object(Closure))
#30 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/BootProviders.php(17): Illuminate\Foundation\Application->boot()
#31 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(203): Illuminate\Foundation\Bootstrap\BootProviders->bootstrap(Object(Illuminate\Foundation\Application))
#32 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(232): Illuminate\Foundation\Application->bootstrapWith(Array)
#33 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(127): Illuminate\Foundation\Http\Kernel->bootstrap()
#34 /var/www/html/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(99): Illuminate\Foundation\Http\Kernel->sendRequestThroughRouter(Object(Illuminate\Http\Request))
#35 /var/www/html/public/index.php(53): Illuminate\Foundation\Http\Kernel->handle(Object(Illuminate\Http\Request))
#36 {main}  `

With contentify 1.2 works perfect bu 2.0 getting errors. Why? Thanks for help! Good CMS!

**Comment by chriskonnertz** [comment] 2016-11-02 17:55
Hi

> 'SQLSTATE[28000] [1045] Access denied for user 'root'@'localhost' (using password: NO)'

This means there is an authentication error when the CMS tries to connect to the database.

Please take a look at this file: `storage/app/datbase.ini` Is everything correct?

**Comment by romcika5** [comment] 2016-11-03 07:13
Ok. Now i'm getting error. `[2016-11-03 08:11:30] production.ERROR: exception 'PDOException' with message 'SQLSTATE[42S02]: Base table or view not found: 1146 Table 'web.config' doesn't exist' in /var/www/html/vendor/laravel/framework/src/Illuminate/Database/Connection.php:333
Stack trace:`

**Comment by romcika5** [comment] 2016-11-03 08:11
Ok i found the problem. I dont know why but i deleted .install file and everythings now working fine! Thanks!

**Comment by chriskonnertz** [comment] 2016-11-03 17:32
Ok cool! Nice to hear that it works now. I close this issue.

**Closed by chriskonnertz** 2016-11-03 17:32 UTC
Labels: help wanted

**Comment by chriskonnertz** [comment] 2016-11-06 09:48
@romcika5 

> Ok i found the problem. I dont know why but i deleted .install file and everythings now working fine! 

It seems like this was caused by a bug. The isntaller was not able to determine if the CMS has been installed or not.

I created a bugfix (you will not need it but others will not have the same problem again):
https://github.com/Contentify/Contentify/commit/5a85aa48ed3ed2ea989179d671fc92e5d7bfcecc
