### ISSUE TITLE
Sorry, something bad happened. Our website has crashed.

### ISSUE THREAD

**Issue by okonstantinyuk** [Contentify/Contentify#355] opened 2018-05-10 15:13 UTC
ERROR
Sorry, something bad happened. Our website has crashed.

Don't worry, we will handle this. In the meantime, make a cup of coffee. And stop crushing our website!

"When you press on the sowing with the Admin how to fix ?"

**Comment by kamohy** [comment] 2018-05-10 15:32
more information? website ? crash-link ?

**Comment by niclasreich** [comment] 2018-05-11 07:05
Duplicate of #345 - solution was already given by @chriskonnertz, @okonstantinyuk

**Comment by chriskonnertz** [comment] 2018-05-11 22:16
Yes it seems to be a duplicate?

**Closed as completed** 2018-06-01 20:13 UTC
Labels: help wanted
